server {
    listen 80;
    server_name watchlist.fgsfds.ai-info.ru;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name watchlist.fgsfds.ai-info.ru;

    ssl_certificate /etc/nginx/certs/watchlist.crt;
    ssl_certificate_key /etc/nginx/certs/watchlist.key;

    root /var/www/watchlist/public;
    index index.php index.html;

    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass laravel:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
